language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then composer install; fi

script:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then vendor/bin/phpunit; else phpunit; fi
