language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
    allow_failures:
        - php: hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then composer self-update; fi

install:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then composer install; fi

script:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then vendor/bin/phpunit; else phpunit; fi
